const prompts = {
	"Disco bowling ball": "discobowlingball.png",
	"Banana using phone booth": "bananaphonebooth.png",
	"Pikachu space suit": "pikachuspace.png",
	"Minion lampshade": "minionlampshade.png",
	"Gigantic inflatable dice": "giantdice.png",
	"Cupcake tornado": "cupcakes.png",
	"Cyberpunk street market": "streetmarket.png",
	"Fluffy cloud chair": "cloudchair.png",
	"Robot birdhouse": "birdhouse.png",
	"Banana hammok": "banana.png",
	"Sandcastle city": "sand.png",
	"Unisoccer": "soccer.png",
	"Purrianist": "piano.png",
	"Master chef dragon": "chef.png",
	"Penguin pizza surfing": "surf.png",
	"Koalas doing yoga": "koala.png",
	"Lions playing fun game": "lion.png",
	"Squirrel rock climbing": "rockclimbing.png",
	"Astronaut in a tutu": "space.png"
}